# Data science coursera track final project
This is my final project in the Coursera track "Data Science". The goal of the project is to create a predictive model on text material. It will predict the third word given two words. This is used in, for example, the SwiftKey app on smartphones that gives suggestions about the next word you are typing.

# Coursera setup, Coursera quote
The goal of this data science specialization has been to give you the basic skills involved with being a data scientist. The goal of this capstone is to mimic the experience of being a data scientist. As a practicing data scientist it is entirely common to get a messy data set, a vague question, and very little instruction on exactly how to analyze the data. Our goal is to give you that same experience but with added support in the form of forums, discussion with instructors, feedback from SwiftKey and Coursera engineers, and a structured problem to solve. We hope that you will take advantage of the opportunity this project affords for you to demonstrate your skills and creativity. 

# Files setup
The contents of the in this supository are ordered in these maps:
- Information: Here you will find detailed information on how I completed the project. You will see I have tried to divide all steps I have taken into functions. I will go over them swiftly with some comments. For detailed information about the working of a function you can delve into the R scripts themselves.
- 00 Global: Here some default scripts are saved. The library file containes all the R libraries that are used throughout the coding in the project. In the settings script, I have gathered all the variables that can be tweaked throughout the project. That way you may change them and run the whole project again.
- 01 Load: Contains the scripst of handling the raw data such as downloading, sampling, loading into R and also the cleaning of the data.
- 02 Exploratory Analaysis: Functions regarding exploring the data for word freqency,etc. are found here
- 03 Modelling: All the models and functions regarding the models (such as validations etc.) are found here
- 04 Analysis: In here, scripts are saved dealing with analysis and testing of models
- 05 ShinyAPP: All files regarding the shiny app
- 06 Presentation: Finally, a presenation was made about all the steps taken towards the final model

Thanks for reading! - Joris Van den Bossche

# Link to the application
[Click here to see the application!](https://jorisvdbos.shinyapps.io/DataScienceTrackFinalProject/)
